android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      sdk: "flutter"
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      -      
